name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # Instalar Node.JS
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
      with:
        node-version: 12.x
     
     # Instalar as dependências NPM/Yarn
    - name: Install dependencies
      run: yarn
     
     # Execultar a build  
    - name: Run build
      run: yarn build
      
      # Copiar pasta dist pra dentro da Digital Ocean
    - name: copy dist to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }} 
        source: "dist"
        target: "test"  
        
      # Substituir o código existente na pasta "dist" pelo novo código   
      # Executar "yarn' na Digital Ocean
      # Executar as migrations do TypeORM -> para caso tenha uma nova tabela
      # Restart no servidor Node.js
      
